export const projects = [
  {
    title: 'Social Book',
    description: "",
    image: 'images/crypto.png',
    tags: ['#.NET Core', '#ReactJS'],
    source: 'https://github.com/SaedMushtaha/SocialBook',
    visit: 'https://cryptonews0.netlify.app/',
    id: 1,
  },
  {
    title: 'Dating App',
    description: "",
    image: 'images/crypto.png',
    tags: ['#ReactJS', '#RapidAPI', '#ChartJS'],
    source: 'https://github.com/SaedMushtaha/CryptoApp',
    visit: 'https://cryptonews0.netlify.app/',
    id: 1,
  },
  {
    title: 'Online Shopping',
    description: "",
    image: 'images/googles.png',
    tags: ['#ReactJS', '#RapidAPI', '#ChatEngine'],
    source: 'https://github.com/SaedMushtaha/googles',
    visit: 'https://google.com',
    id: 3,
  },
  // {
  //   title: 'Real Estate Market',
  //   description: "",
  //   image: 'images/realestate.png',
  //   tags: ['#ReactJS', '#RapidAPI', '#NextJS'],
  //   source: 'https://github.com/SaedMushtaha/realestateworld',
  //   visit: 'https://realesattemarket.netlify.app',
  //   id: 4,
  // },
  // {
  //   title: 'Sencard - medical service network',
  //   description: "",
  //   image: '/images/sencard.png',
  //   tags: ['React', 'ChatEngine', 'Firebase'],
  //   source: '#',
  //   visit: 'https://online.sencard.com.tr/',
  //   id: 5,
  // },
  // {
  //   title: 'UCA school website',
  //   description: "",
  //   image: '/images/uca.jpg',
  //   tags: ['React', 'ChatEngine', 'Firebase'],
  //   source: '',
  //   visit: 'https://www.uca.edu.kw/',
  //   id: 6,
  // },
  // {
  //   title: 'Al hussan Group',
  //   description: "",
  //   image: '/images/hussan.jpg',
  //   tags: ['React', 'ChatEngine', 'Firebase'],
  //   source: '#',
  //   visit: 'https://international.alhussan.edu.sa/',
  //   id: 7,
  // },
  // {
  //   title: 'Al Najat Charity',
  //   description: "",
  //   image: '/images/najat.jpg',
  //   tags: ['React', 'ChatEngine', 'Firebase'],
  //   source: '#',
  //   visit: 'https://google.com',
  //   id: 8,
  // },
  // {
  //   title: 'Al Kifah School',
  //   description: "",
  //   image: '/images/4.jpg',
  //   tags: ['React', 'ChatEngine', 'Firebase'],
  //   source: '',
  //   visit: 'http://alkifah.edu.sa/en/', // http://www.mss.jo/en/
  //   id: 9,
  // },
  // {
  //   title: 'Health insurance market',
  //   description: "",
  //   image: '/images/dental.png',
  //   tags: ['React', 'ChatEngine', 'Firebase'],
  //   source: '',
  //   visit: 'https://market.sencard.com.tr/',
  //   id: 2,
  // },
];

export const TimeLineData = [
  { year: 2018, text: 'Graduated from the University', },
  { year: 2019, text: 'Found my first job as a junior Web Developer', },
  { year: 2020, text: 'Worked as a freelance developer', },
  { year: 2021, text: 'Shared my projects with the world', },
  { year: 2022, text: 'Started my own platform', },
];